# -*- coding: utf-8 -*-
"""Leave.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15V23_kXhtFz7L76H_rHSLncdVYQz3JA1
"""

import streamlit as st

st.set_page_config(page_title="Leave Application Generator", layout="centered")

st.title("📝 Leave Application Generator")

# Inputs
your_name = st.text_input("Your Name")
designation = st.text_input("Your Designation")
manager_name = st.text_input("Manager's Name")
leave_dates = st.text_input("Leave Date(s)", placeholder="e.g., May 1–3, 2025")
leave_reason = st.text_area("Reason for Leave", placeholder="e.g., medical reasons, family function...")
proof_document = st.text_input("Supporting Document", placeholder="e.g., medical certificate")

# Generate letter
if st.button("Generate Leave Application"):
    if not all([your_name, designation, manager_name, leave_dates, leave_reason]):
        st.warning("Please fill out all required fields.")
    else:
        leave_letter = f"""\
Subject : Leave Application for {leave_dates}

Dear {manager_name},

I hope you are doing well.

I would like to request leave for {leave_dates} due to {leave_reason}.
I have attached {proof_document or "the relevant document"} as proof for your reference.

I will ensure that all my responsibilities are managed during my absence.

Thank you for your consideration.

Best regards,
{your_name}
{designation}
"""
        st.subheader("📄 Your Leave Application")
        st.code(leave_letter, language='markdown')
